# Generated by Django 3.1 on 2020-09-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200905_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('address', models.CharField(max_length=100)),
                ('books', models.ManyToManyField(to='main.Book')),
            ],
        ),
    ]
